version: '1.0.{build}-{branch}'
before_build:
  - dotnet msbuild /t:restore PassSharp.sln
build:
  project: PassSharp.sln
  publish_nuget: true
deploy:
- provider: NuGet
  api_key:
    secure: NzqoRXcIEgz85NVKo/Z5MJwOVq/Sew2HRITWGmoSgpkmSv1uLfOXXcMSz2moTdkw
  skip_symbols: true
  on:
    branch: master
    appveyor_repo_tag: true